CREATE TABLE "Permissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Category" text NOT NULL,
    "IsCritical" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "LastModifiedBy" integer,
    "DeletedBy" integer,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
);


CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "HierarchyLevel" integer NOT NULL,
    "IsSystemRole" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "LastModifiedBy" integer,
    "DeletedBy" integer,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);


CREATE TABLE "VehicleTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_VehicleTypes" PRIMARY KEY ("Id")
);


CREATE TABLE "RolePermissions" (
    "RoleId" integer NOT NULL,
    "PermissionId" integer NOT NULL,
    "GrantedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("RoleId", "PermissionId"),
    CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Answers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FormSubmissionId" integer NOT NULL,
    "FormFieldId" integer NOT NULL,
    "FieldValue" text NOT NULL,
    "Notes" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Answers" PRIMARY KEY ("Id")
);


CREATE TABLE "Attachments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FormSubmissionId" integer NOT NULL,
    "FormFieldId" integer,
    "FileName" text NOT NULL,
    "ContentType" text NOT NULL,
    "FileSize" bigint NOT NULL,
    "FileData" bytea NOT NULL,
    "FilePath" text NOT NULL,
    "Description" text NOT NULL,
    "EvidenceType" text NOT NULL,
    "UploadedByUserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "LastModifiedBy" integer,
    "DeletedBy" integer,
    CONSTRAINT "PK_Attachments" PRIMARY KEY ("Id")
);


CREATE TABLE "AuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "EntityName" text NOT NULL,
    "EntityId" integer NOT NULL,
    "Action" text NOT NULL,
    "Description" text NOT NULL,
    "OldValues" text NOT NULL,
    "NewValues" text NOT NULL,
    "IpAddress" text NOT NULL,
    "UserAgent" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);


CREATE TABLE "Crews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "ManagedByUserId" integer NOT NULL,
    "Department" text NOT NULL,
    "Location" text NOT NULL,
    "MemberCount" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "LastModifiedBy" integer,
    "DeletedBy" integer,
    CONSTRAINT "PK_Crews" PRIMARY KEY ("Id")
);


CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "FullName" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "LastLogin" timestamp with time zone,
    "CrewId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "LastModifiedBy" integer,
    "DeletedBy" integer,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Crews_CrewId" FOREIGN KEY ("CrewId") REFERENCES "Crews" ("Id") ON DELETE SET NULL
);


CREATE TABLE "ExportHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ExportedByUserId" integer NOT NULL,
    "ExportType" text NOT NULL,
    "FileFormat" text NOT NULL,
    "ExportedEntity" text NOT NULL,
    "FilterDescription" text NOT NULL,
    "FileName" text NOT NULL,
    "FilePath" text NOT NULL,
    "FileSizeInBytes" bigint NOT NULL,
    "RecordCount" integer NOT NULL,
    "DurationInMs" bigint NOT NULL,
    "Status" text NOT NULL,
    "ErrorMessage" text NOT NULL,
    "IpAddress" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "LastModifiedBy" integer,
    "DeletedBy" integer,
    CONSTRAINT "PK_ExportHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExportHistories_Users_ExportedByUserId" FOREIGN KEY ("ExportedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "FormTemplates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "FormType" text NOT NULL,
    "Version" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "RequiresSignature" boolean NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "CreatedByUserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "LastModifiedBy" integer,
    "DeletedBy" integer,
    CONSTRAINT "PK_FormTemplates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FormTemplates_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "RefreshTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Token" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IssuedFromIp" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    "IsUsed" boolean NOT NULL,
    "IsRevoked" boolean NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    "AssignedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "FormFields" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FormTemplateId" integer NOT NULL,
    "Label" text NOT NULL,
    "Description" text NOT NULL,
    "FieldType" text NOT NULL,
    "IsRequired" boolean NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "Category" text NOT NULL,
    "Options" text NOT NULL,
    "ValidationRules" text NOT NULL,
    "DefaultValue" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "LastModifiedBy" integer,
    "DeletedBy" integer,
    CONSTRAINT "PK_FormFields" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FormFields_FormTemplates_FormTemplateId" FOREIGN KEY ("FormTemplateId") REFERENCES "FormTemplates" ("Id") ON DELETE CASCADE
);


CREATE TABLE "FormSubmissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FormTemplateId" integer NOT NULL,
    "SubmittedByUserId" integer NOT NULL,
    "AssignedToCrewId" integer,
    "ActivityLocation" text NOT NULL,
    "ActivityDate" timestamp with time zone NOT NULL,
    "ObservationsByRespondent" text NOT NULL,
    "ObservationsByRectifier" text NOT NULL,
    "VerifiedAt" timestamp with time zone,
    "VerifiedByUserId" integer,
    "RequiresReview" boolean NOT NULL,
    "VehicleTypeId" integer,
    "ClosedAt" timestamp with time zone,
    "ClosedByUserId" integer,
    "ApprovedByIngenieroId" integer,
    "ApprovedByIngenieroAt" timestamp with time zone,
    "ApprovedBySupervisorId" integer,
    "ApprovedBySupervisorAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "LastModifiedBy" integer,
    "DeletedBy" integer,
    "Status" text NOT NULL,
    "StatusComment" text NOT NULL,
    "LastStatusChangeAt" timestamp with time zone,
    "LastStatusChangedBy" integer,
    CONSTRAINT "PK_FormSubmissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FormSubmissions_Crews_AssignedToCrewId" FOREIGN KEY ("AssignedToCrewId") REFERENCES "Crews" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_FormSubmissions_FormTemplates_FormTemplateId" FOREIGN KEY ("FormTemplateId") REFERENCES "FormTemplates" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FormSubmissions_Users_ClosedByUserId" FOREIGN KEY ("ClosedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_FormSubmissions_Users_SubmittedByUserId" FOREIGN KEY ("SubmittedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FormSubmissions_Users_VerifiedByUserId" FOREIGN KEY ("VerifiedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_FormSubmissions_VehicleTypes_VehicleTypeId" FOREIGN KEY ("VehicleTypeId") REFERENCES "VehicleTypes" ("Id") ON DELETE SET NULL
);


INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (1, 'User Management', TIMESTAMPTZ '2026-07-07T04:51:33.513864Z', NULL, NULL, 'Crear nuevo usuario', TRUE, TRUE, FALSE, NULL, 'CREATE_USER', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (2, 'User Management', TIMESTAMPTZ '2026-07-07T04:51:33.513868Z', NULL, NULL, 'Editar usuario existente', TRUE, FALSE, FALSE, NULL, 'EDIT_USER', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (3, 'User Management', TIMESTAMPTZ '2026-07-07T04:51:33.513868Z', NULL, NULL, 'Eliminar usuario', TRUE, TRUE, FALSE, NULL, 'DELETE_USER', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (4, 'User Management', TIMESTAMPTZ '2026-07-07T04:51:33.513868Z', NULL, NULL, 'Ver detalles del usuario', TRUE, FALSE, FALSE, NULL, 'VIEW_USER', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (5, 'Crew Management', TIMESTAMPTZ '2026-07-07T04:51:33.513868Z', NULL, NULL, 'Crear nueva cuadrilla', TRUE, TRUE, FALSE, NULL, 'CREATE_CREW', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (6, 'Crew Management', TIMESTAMPTZ '2026-07-07T04:51:33.513868Z', NULL, NULL, 'Editar cuadrilla', TRUE, FALSE, FALSE, NULL, 'EDIT_CREW', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (7, 'Crew Management', TIMESTAMPTZ '2026-07-07T04:51:33.513868Z', NULL, NULL, 'Eliminar cuadrilla', TRUE, TRUE, FALSE, NULL, 'DELETE_CREW', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (8, 'Crew Management', TIMESTAMPTZ '2026-07-07T04:51:33.513869Z', NULL, NULL, 'Ver cuadrilla', TRUE, FALSE, FALSE, NULL, 'VIEW_CREW', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (9, 'Form Management', TIMESTAMPTZ '2026-07-07T04:51:33.513869Z', NULL, NULL, 'Crear nuevo formulario', TRUE, TRUE, FALSE, NULL, 'CREATE_FORM', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (10, 'Form Management', TIMESTAMPTZ '2026-07-07T04:51:33.513869Z', NULL, NULL, 'Editar formulario', TRUE, FALSE, FALSE, NULL, 'EDIT_FORM', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (11, 'Form Management', TIMESTAMPTZ '2026-07-07T04:51:33.513869Z', NULL, NULL, 'Responder/diligenciar formulario', TRUE, FALSE, FALSE, NULL, 'SUBMIT_FORM', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (12, 'Form Management', TIMESTAMPTZ '2026-07-07T04:51:33.513869Z', NULL, NULL, 'Verificar y rectificar formulario', TRUE, FALSE, FALSE, NULL, 'VERIFY_FORM', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (13, 'Form Management', TIMESTAMPTZ '2026-07-07T04:51:33.513869Z', NULL, NULL, 'Ver formulario', TRUE, FALSE, FALSE, NULL, 'VIEW_FORM', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (14, 'Reports & Export', TIMESTAMPTZ '2026-07-07T04:51:33.513869Z', NULL, NULL, 'Exportar a Excel', TRUE, FALSE, FALSE, NULL, 'EXPORT_EXCEL', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (15, 'Reports & Export', TIMESTAMPTZ '2026-07-07T04:51:33.51387Z', NULL, NULL, 'Exportar a PDF', TRUE, FALSE, FALSE, NULL, 'EXPORT_PDF', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (16, 'Reports & Export', TIMESTAMPTZ '2026-07-07T04:51:33.51387Z', NULL, NULL, 'Ver reportes', TRUE, FALSE, FALSE, NULL, 'VIEW_REPORTS', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (17, 'Audit & Security', TIMESTAMPTZ '2026-07-07T04:51:33.51387Z', NULL, NULL, 'Ver registro de auditoría', TRUE, TRUE, FALSE, NULL, 'VIEW_AUDIT_LOG', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (18, 'Audit & Security', TIMESTAMPTZ '2026-07-07T04:51:33.51387Z', NULL, NULL, 'Gestionar roles y permisos', TRUE, TRUE, FALSE, NULL, 'MANAGE_ROLES', NULL);
INSERT INTO "Permissions" ("Id", "Category", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "IsActive", "IsCritical", "IsDeleted", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (19, 'Audit & Security', TIMESTAMPTZ '2026-07-07T04:51:33.51387Z', NULL, NULL, 'Ver historial de exportaciones', TRUE, FALSE, FALSE, NULL, 'VIEW_EXPORT_HISTORY', NULL);


INSERT INTO "Roles" ("Id", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "HierarchyLevel", "IsActive", "IsDeleted", "IsSystemRole", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (1, TIMESTAMPTZ '2026-07-07T04:51:33.51296Z', NULL, NULL, 'Desarrollador - Control total del sistema', 0, TRUE, FALSE, TRUE, NULL, 'DEV', NULL);
INSERT INTO "Roles" ("Id", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "HierarchyLevel", "IsActive", "IsDeleted", "IsSystemRole", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (2, TIMESTAMPTZ '2026-07-07T04:51:33.512961Z', NULL, NULL, 'Administrador de Software - Gestión de usuarios y configuración', 1, TRUE, FALSE, TRUE, NULL, 'SOFTWARE', NULL);
INSERT INTO "Roles" ("Id", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "HierarchyLevel", "IsActive", "IsDeleted", "IsSystemRole", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (3, TIMESTAMPTZ '2026-07-07T04:51:33.512961Z', NULL, NULL, 'Ingeniero Mecánico - Responde formularios mecánicos', 2, TRUE, FALSE, TRUE, NULL, 'INGENIERO_MECANICO', NULL);
INSERT INTO "Roles" ("Id", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "HierarchyLevel", "IsActive", "IsDeleted", "IsSystemRole", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (4, TIMESTAMPTZ '2026-07-07T04:51:33.512962Z', NULL, NULL, 'Supervisor HSEQ - Responde y supervisa formularios de seguridad', 2, TRUE, FALSE, TRUE, NULL, 'SUPERVISOR_HSEQ', NULL);
INSERT INTO "Roles" ("Id", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "HierarchyLevel", "IsActive", "IsDeleted", "IsSystemRole", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (5, TIMESTAMPTZ '2026-07-07T04:51:33.512962Z', NULL, NULL, 'Cuadrilla - Verifica y rectifica información', 3, TRUE, FALSE, TRUE, NULL, 'CUADRILLA', NULL);
INSERT INTO "Roles" ("Id", "CreatedAt", "DeletedAt", "DeletedBy", "Description", "HierarchyLevel", "IsActive", "IsDeleted", "IsSystemRole", "LastModifiedBy", "Name", "UpdatedAt")
VALUES (6, TIMESTAMPTZ '2026-07-07T04:51:33.512962Z', NULL, NULL, 'Jefe de Mantenimiento - Supervisión general de mantenimiento y flota', 2, TRUE, FALSE, TRUE, NULL, 'JEFE_MTTO', NULL);


INSERT INTO "Users" ("Id", "CreatedAt", "CrewId", "DeletedAt", "DeletedBy", "Email", "FullName", "IsActive", "IsDeleted", "LastLogin", "LastModifiedBy", "PasswordHash", "UpdatedAt", "Username")
VALUES (1, TIMESTAMPTZ '2026-07-07T04:51:33.517381Z', NULL, NULL, NULL, 'admin@autocheck.com', 'Administrador del Sistema', TRUE, FALSE, NULL, NULL, '$2a$11$8DZSIblN9F/gw02upCV3B.AnN.HKV2lzqYdP/zqt8pZMSd5LBvota', NULL, 'Admin');


INSERT INTO "VehicleTypes" ("Id", "CreatedAt", "Description", "DisplayOrder", "IsActive", "Name")
VALUES (1, TIMESTAMPTZ '2026-07-07T04:51:33.511612Z', 'Vehículo utilitario ligero', 1, TRUE, 'Camioneta');
INSERT INTO "VehicleTypes" ("Id", "CreatedAt", "Description", "DisplayOrder", "IsActive", "Name")
VALUES (2, TIMESTAMPTZ '2026-07-07T04:51:33.511638Z', 'Vehículo de carga pesada', 2, TRUE, 'Camión');
INSERT INTO "VehicleTypes" ("Id", "CreatedAt", "Description", "DisplayOrder", "IsActive", "Name")
VALUES (3, TIMESTAMPTZ '2026-07-07T04:51:33.511638Z', 'Vehículo de volteo para materiales', 3, TRUE, 'Volqueta');
INSERT INTO "VehicleTypes" ("Id", "CreatedAt", "Description", "DisplayOrder", "IsActive", "Name")
VALUES (4, TIMESTAMPTZ '2026-07-07T04:51:33.511638Z', 'Vehículo de pasajeros', 4, TRUE, 'Automóvil');
INSERT INTO "VehicleTypes" ("Id", "CreatedAt", "Description", "DisplayOrder", "IsActive", "Name")
VALUES (5, TIMESTAMPTZ '2026-07-07T04:51:33.511638Z', 'Motocicleta', 5, TRUE, 'Moto');
INSERT INTO "VehicleTypes" ("Id", "CreatedAt", "Description", "DisplayOrder", "IsActive", "Name")
VALUES (6, TIMESTAMPTZ '2026-07-07T04:51:33.511638Z', 'Excavadoras, retroexcavadoras, etc.', 6, TRUE, 'Maquinaria Pesada');


INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (1, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516656Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (2, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516718Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (3, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516718Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (4, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516718Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (5, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516718Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (6, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516718Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (7, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516718Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (8, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516718Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (9, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516718Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (10, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516719Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (11, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516719Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (12, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516719Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (13, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516719Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (14, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516719Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (15, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516719Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (16, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516719Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (17, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516719Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (18, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516719Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (19, 1, TIMESTAMPTZ '2026-07-07T04:51:33.516719Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (1, 2, TIMESTAMPTZ '2026-07-07T04:51:33.51672Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (2, 2, TIMESTAMPTZ '2026-07-07T04:51:33.51672Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (3, 2, TIMESTAMPTZ '2026-07-07T04:51:33.51672Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (4, 2, TIMESTAMPTZ '2026-07-07T04:51:33.51672Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (5, 2, TIMESTAMPTZ '2026-07-07T04:51:33.516721Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (6, 2, TIMESTAMPTZ '2026-07-07T04:51:33.516721Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (7, 2, TIMESTAMPTZ '2026-07-07T04:51:33.516721Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (8, 2, TIMESTAMPTZ '2026-07-07T04:51:33.516721Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (9, 2, TIMESTAMPTZ '2026-07-07T04:51:33.516721Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (10, 2, TIMESTAMPTZ '2026-07-07T04:51:33.516721Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (13, 2, TIMESTAMPTZ '2026-07-07T04:51:33.516721Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (14, 2, TIMESTAMPTZ '2026-07-07T04:51:33.516721Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (15, 2, TIMESTAMPTZ '2026-07-07T04:51:33.516721Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (16, 2, TIMESTAMPTZ '2026-07-07T04:51:33.516722Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (17, 2, TIMESTAMPTZ '2026-07-07T04:51:33.516722Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (18, 2, TIMESTAMPTZ '2026-07-07T04:51:33.516722Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (19, 2, TIMESTAMPTZ '2026-07-07T04:51:33.516722Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (11, 3, TIMESTAMPTZ '2026-07-07T04:51:33.516722Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (13, 3, TIMESTAMPTZ '2026-07-07T04:51:33.516722Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (14, 3, TIMESTAMPTZ '2026-07-07T04:51:33.516722Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (15, 3, TIMESTAMPTZ '2026-07-07T04:51:33.516722Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (11, 4, TIMESTAMPTZ '2026-07-07T04:51:33.516722Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (13, 4, TIMESTAMPTZ '2026-07-07T04:51:33.516723Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (14, 4, TIMESTAMPTZ '2026-07-07T04:51:33.516723Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (15, 4, TIMESTAMPTZ '2026-07-07T04:51:33.516723Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (12, 5, TIMESTAMPTZ '2026-07-07T04:51:33.516723Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (13, 5, TIMESTAMPTZ '2026-07-07T04:51:33.516723Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (11, 6, TIMESTAMPTZ '2026-07-07T04:51:33.516723Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (12, 6, TIMESTAMPTZ '2026-07-07T04:51:33.516723Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (13, 6, TIMESTAMPTZ '2026-07-07T04:51:33.516723Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (14, 6, TIMESTAMPTZ '2026-07-07T04:51:33.516723Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (15, 6, TIMESTAMPTZ '2026-07-07T04:51:33.516724Z', TRUE);
INSERT INTO "RolePermissions" ("PermissionId", "RoleId", "GrantedAt", "IsActive")
VALUES (16, 6, TIMESTAMPTZ '2026-07-07T04:51:33.516724Z', TRUE);


INSERT INTO "UserRoles" ("RoleId", "UserId", "AssignedAt", "ExpiresAt", "IsActive")
VALUES (1, 1, TIMESTAMPTZ '2026-07-07T04:51:33.517381Z', NULL, TRUE);


CREATE INDEX "IX_Answers_FormFieldId" ON "Answers" ("FormFieldId");


CREATE INDEX "IX_Answers_FormSubmissionId" ON "Answers" ("FormSubmissionId");


CREATE INDEX "IX_Attachments_FormFieldId" ON "Attachments" ("FormFieldId");


CREATE INDEX "IX_Attachments_FormSubmissionId" ON "Attachments" ("FormSubmissionId");


CREATE INDEX "IX_Attachments_UploadedByUserId" ON "Attachments" ("UploadedByUserId");


CREATE INDEX "IX_AuditLogs_Action" ON "AuditLogs" ("Action");


CREATE INDEX "IX_AuditLogs_CreatedAt" ON "AuditLogs" ("CreatedAt");


CREATE INDEX "IX_AuditLogs_EntityName" ON "AuditLogs" ("EntityName");


CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");


CREATE INDEX "IX_Crews_Department" ON "Crews" ("Department");


CREATE INDEX "IX_Crews_ManagedByUserId" ON "Crews" ("ManagedByUserId");


CREATE UNIQUE INDEX "IX_Crews_Name" ON "Crews" ("Name");


CREATE INDEX "IX_ExportHistories_CreatedAt" ON "ExportHistories" ("CreatedAt");


CREATE INDEX "IX_ExportHistories_ExportedByUserId" ON "ExportHistories" ("ExportedByUserId");


CREATE INDEX "IX_FormFields_FormTemplateId" ON "FormFields" ("FormTemplateId");


CREATE INDEX "IX_FormSubmissions_AssignedToCrewId" ON "FormSubmissions" ("AssignedToCrewId");


CREATE INDEX "IX_FormSubmissions_ClosedByUserId" ON "FormSubmissions" ("ClosedByUserId");


CREATE INDEX "IX_FormSubmissions_CreatedAt" ON "FormSubmissions" ("CreatedAt");


CREATE INDEX "IX_FormSubmissions_FormTemplateId" ON "FormSubmissions" ("FormTemplateId");


CREATE INDEX "IX_FormSubmissions_Status" ON "FormSubmissions" ("Status");


CREATE INDEX "IX_FormSubmissions_SubmittedByUserId" ON "FormSubmissions" ("SubmittedByUserId");


CREATE INDEX "IX_FormSubmissions_SubmittedByUserId_CreatedAt" ON "FormSubmissions" ("SubmittedByUserId", "CreatedAt");


CREATE INDEX "IX_FormSubmissions_VehicleTypeId" ON "FormSubmissions" ("VehicleTypeId");


CREATE INDEX "IX_FormSubmissions_VerifiedByUserId" ON "FormSubmissions" ("VerifiedByUserId");


CREATE INDEX "IX_FormTemplates_CreatedByUserId" ON "FormTemplates" ("CreatedByUserId");


CREATE INDEX "IX_FormTemplates_FormType" ON "FormTemplates" ("FormType");


CREATE INDEX "IX_FormTemplates_Name" ON "FormTemplates" ("Name");


CREATE INDEX "IX_Permissions_Category" ON "Permissions" ("Category");


CREATE UNIQUE INDEX "IX_Permissions_Name" ON "Permissions" ("Name");


CREATE INDEX "IX_RefreshTokens_ExpiresAt" ON "RefreshTokens" ("ExpiresAt");


CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");


CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");


CREATE INDEX "IX_RolePermissions_PermissionId" ON "RolePermissions" ("PermissionId");


CREATE INDEX "IX_Roles_HierarchyLevel" ON "Roles" ("HierarchyLevel");


CREATE UNIQUE INDEX "IX_Roles_Name" ON "Roles" ("Name");


CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");


CREATE INDEX "IX_Users_CrewId" ON "Users" ("CrewId");


CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");


CREATE INDEX "IX_Users_IsActive" ON "Users" ("IsActive");


CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");


CREATE INDEX "IX_VehicleTypes_IsActive" ON "VehicleTypes" ("IsActive");


CREATE UNIQUE INDEX "IX_VehicleTypes_Name" ON "VehicleTypes" ("Name");


ALTER TABLE "Answers" ADD CONSTRAINT "FK_Answers_FormFields_FormFieldId" FOREIGN KEY ("FormFieldId") REFERENCES "FormFields" ("Id") ON DELETE RESTRICT;


ALTER TABLE "Answers" ADD CONSTRAINT "FK_Answers_FormSubmissions_FormSubmissionId" FOREIGN KEY ("FormSubmissionId") REFERENCES "FormSubmissions" ("Id") ON DELETE CASCADE;


ALTER TABLE "Attachments" ADD CONSTRAINT "FK_Attachments_FormFields_FormFieldId" FOREIGN KEY ("FormFieldId") REFERENCES "FormFields" ("Id") ON DELETE SET NULL;


ALTER TABLE "Attachments" ADD CONSTRAINT "FK_Attachments_FormSubmissions_FormSubmissionId" FOREIGN KEY ("FormSubmissionId") REFERENCES "FormSubmissions" ("Id") ON DELETE CASCADE;


ALTER TABLE "Attachments" ADD CONSTRAINT "FK_Attachments_Users_UploadedByUserId" FOREIGN KEY ("UploadedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;


ALTER TABLE "AuditLogs" ADD CONSTRAINT "FK_AuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;


ALTER TABLE "Crews" ADD CONSTRAINT "FK_Crews_Users_ManagedByUserId" FOREIGN KEY ("ManagedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;


SELECT setval(
    pg_get_serial_sequence('"Permissions"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Permissions") + 1,
        nextval(pg_get_serial_sequence('"Permissions"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Roles"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Roles") + 1,
        nextval(pg_get_serial_sequence('"Roles"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Users"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Users") + 1,
        nextval(pg_get_serial_sequence('"Users"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"VehicleTypes"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "VehicleTypes") + 1,
        nextval(pg_get_serial_sequence('"VehicleTypes"', 'Id'))),
    false);


